# Generated by Django 4.2.11 on 2024-06-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_partnerbranch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerbranch',
            unique_together={('partner', 'name', 'is_head_office', 'is_active')},
        ),
    ]
