# Generated by Django 4.2.11 on 2024-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Passport Number'),
        ),
    ]
