# Generated by Django 4.2.11 on 2024-06-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0025_assessmentdiscovery'),
        ('users', '0007_alter_student_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.level'),
        ),
    ]
