# Generated by Django 4.2.11 on 2024-06-25 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0026_alter_assessmentdiscovery_student'),
        ('users', '0008_student_study_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGStudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('passing_month', models.IntegerField(blank=True, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('tenth_marks', models.IntegerField(blank=True, null=True)),
                ('twelfth_english_marks', models.IntegerField(blank=True, null=True)),
                ('english_overall', models.CharField(blank=True, max_length=150, null=True)),
                ('speaking', models.CharField(blank=True, max_length=150, null=True)),
                ('writing', models.CharField(blank=True, max_length=150, null=True)),
                ('reading', models.CharField(blank=True, max_length=150, null=True)),
                ('listening', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_pathway', models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('intermediate', 'Intermediate')], max_length=100, null=True)),
                ('overall_marks', models.IntegerField(blank=True, help_text='Twelfth/Diploma Overall marks', null=True)),
                ('twelfth_math_marks', models.IntegerField(blank=True, null=True)),
                ('twelfth_best_four_marks', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.board')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('english_test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.englishtesttype')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.state')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.stream')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('sub_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.substream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PGStudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('passing_month', models.IntegerField(blank=True, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('tenth_marks', models.IntegerField(blank=True, null=True)),
                ('twelfth_english_marks', models.IntegerField(blank=True, null=True)),
                ('english_overall', models.CharField(blank=True, max_length=150, null=True)),
                ('speaking', models.CharField(blank=True, max_length=150, null=True)),
                ('writing', models.CharField(blank=True, max_length=150, null=True)),
                ('reading', models.CharField(blank=True, max_length=150, null=True)),
                ('listening', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_pathway', models.CharField(blank=True, choices=[('intermediate_ug', '12th And UG'), ('diploma_ug', 'Diploma And UG'), ('level_diploma', 'Diploma Level (6/7)')], max_length=100, null=True)),
                ('diploma_overall_marks', models.IntegerField(blank=True, null=True)),
                ('ug_overall_marks', models.IntegerField(blank=True, null=True)),
                ('level_diploma_marks', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.board')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('english_test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.englishtesttype')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.state')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.stream')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('sub_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.substream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
