# Generated by Django 4.2.11 on 2024-06-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0026_alter_assessmentdiscovery_student'),
        ('users', '0009_ugstudentacademic_pgstudentacademic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgstudentacademic',
            name='passing_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.year'),
        ),
        migrations.AlterField(
            model_name='ugstudentacademic',
            name='passing_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.year'),
        ),
    ]
