# Generated by Django 4.2.11 on 2024-07-16 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0026_alter_assessmentdiscovery_student'),
        ('users', '0013_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('communication_type', models.CharField(choices=[('mobile', 'Mobile'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('communication_value', models.CharField(max_length=255)),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.country')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partner')),
            ],
            options={
                'unique_together': {('partner', 'communication_type', 'communication_value')},
            },
        ),
    ]
