# Generated by Django 4.2.11 on 2024-07-19 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_partnercommunication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercommunication',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerbranch'),
        ),
    ]
