# Generated by Django 4.2.11 on 2024-07-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_partnercommunication_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_mobile_country_code', to='paceapp.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='whatsapp_country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_whatsapp_country_code', to='paceapp.country'),
        ),
    ]
