# Generated by Django 4.2.11 on 2024-07-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0032_remove_assessmentdiscovery_courses_and_more'),
        ('users', '0019_alter_partner_address_alter_partner_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='mobile_country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_mobile_country_code', to='paceapp.country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='whatsapp_country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_whatsapp_country_code', to='paceapp.country'),
        ),
    ]
