# Generated by Django 4.2.11 on 2024-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_partner_mobile_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
