# Generated by Django 4.2.11 on 2024-07-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_applicationremark'),
        ('paceapp', '0032_remove_assessmentdiscovery_courses_and_more'),
        ('users', '0021_alter_partner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='core.statustype'),
        ),
        migrations.AddField(
            model_name='student',
            name='english_test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='paceapp.englishtesttype'),
        ),
        migrations.AddField(
            model_name='student',
            name='study_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_study_country', to='paceapp.country'),
        ),
    ]
