# Generated by Django 4.2.11 on 2024-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_partner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person Name'),
        ),
    ]
