# Generated by Django 4.2.11 on 2024-07-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0033_alter_universityintake_options_and_more'),
        ('users', '0024_partner_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_regions',
            field=models.ManyToManyField(blank=True, to='paceapp.region'),
        ),
    ]
