# Generated by Django 4.2.11 on 2024-07-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_employee_emergency_contact_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Mobile Number'),
        ),
    ]
