# Generated by Django 4.2.11 on 2024-08-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_employee_emergency_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
