# Generated by Django 4.2.11 on 2024-09-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0039_universityagreement'),
        ('users', '0030_applicationmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgstudentacademic',
            name='country',
            field=models.ForeignKey(help_text='Country of Citizenship', on_delete=django.db.models.deletion.CASCADE, to='paceapp.country'),
        ),
        migrations.AlterField(
            model_name='ugstudentacademic',
            name='country',
            field=models.ForeignKey(help_text='Country of Citizenship', on_delete=django.db.models.deletion.CASCADE, to='paceapp.country'),
        ),
    ]
