# Generated by Django 4.2.11 on 2024-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_pgstudentacademic_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(blank=True, choices=[('onshore', 'Onshore'), ('offshore', 'Offshore')], max_length=20, null=True, verbose_name='Type of Student'),
        ),
    ]
