# Generated by Django 4.2.11 on 2024-09-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0039_universityagreement'),
        ('users', '0032_student_email_student_mobile_number_student_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'partner', 'date_of_birth', 'passport_number', 'study_country')},
        ),
    ]
