# Generated by Django 4.2.11 on 2024-09-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_partner_owner_email_partner_owner_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentacademic',
            name='work_experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ugstudentacademic',
            name='work_experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
