# Generated by Django 4.2.11 on 2024-09-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_partner_on_boarded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='legal_name',
            field=models.CharField(help_text='Company Legal Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(help_text='Company Trade Name', max_length=255, unique=True),
        ),
    ]
