# Generated by Django 4.2.11 on 2024-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_partner_blacklisted_partner_legal_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['mobile_number'], name='users_emplo_mobile__c39bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['whatsapp_number'], name='users_emplo_whatsap_867dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['assigned_country'], name='users_emplo_assigne_aa05a5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='users_emplo_user_id_8f2eca_idx'),
        ),
    ]
