# Generated by Django 4.2.11 on 2024-10-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_partneragreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='agreement',
        ),
    ]
