# Generated by Django 4.2.11 on 2024-10-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_partner_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment_requested',
            field=models.BooleanField(default=False),
        ),
    ]
