# Generated by Django 4.2.11 on 2024-10-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_student_assessment_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
