# Generated by Django 4.2.11 on 2024-11-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_employee_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
    ]
