# Generated by Django 4.2.11 on 2024-11-25 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_partner_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbranch',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_branch', to=settings.AUTH_USER_MODEL),
        ),
    ]
