# Generated by Django 4.2.11 on 2024-07-17 07:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('target_value', models.IntegerField()),
                ('rm_count', models.IntegerField(help_text='Regional Marketing Head')),
                ('assessment_officer_count', models.IntegerField()),
                ('application_manager_count', models.IntegerField()),
                ('interviewer_count', models.IntegerField()),
                ('visa_officer_count', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
