# Generated by Django 4.2.11 on 2024-07-17 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0030_university_color_code_university_is_premium'),
        ('core', '0004_documenttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSupportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('intake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.intake')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documenttemplate')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
