# Generated by Django 4.2.11 on 2024-07-18 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0030_university_color_code_university_is_premium'),
        ('core', '0006_statustype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySpecificStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('status_types', models.ManyToManyField(related_name='country_specific_statuses', to='core.statustype')),
            ],
            options={
                'indexes': [models.Index(fields=['country'], name='core_countr_country_b03592_idx')],
            },
        ),
    ]
