# Generated by Django 4.2.11 on 2024-07-18 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0030_university_color_code_university_is_premium'),
        ('users', '0016_partnercommunication_is_active'),
        ('core', '0007_countryspecificstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.course')),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statustype')),
                ('intake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.intake')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.year')),
            ],
            options={
                'indexes': [models.Index(fields=['course'], name='core_applic_course__c08e88_idx')],
            },
        ),
    ]
