# Generated by Django 4.2.11 on 2024-07-26 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetcom', '0007_remove_meeting_assigned_to_meeting_assigned_to'),
        ('core', '0013_genericfollowup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericfollowup',
            name='contact_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='meetcom.communicationtype'),
        ),
        migrations.AlterField(
            model_name='genericfollowup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
    ]
