# Generated by Django 4.2.11 on 2024-08-08 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0037_assessmentdiscovery_created_by'),
        ('core', '0019_genericdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySpecificLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('levels', models.ManyToManyField(related_name='country_specific_levels', to='paceapp.level')),
            ],
            options={
                'indexes': [models.Index(fields=['country'], name='core_countr_country_ca9b3c_idx')],
            },
        ),
    ]
