# Generated by Django 4.2.11 on 2024-08-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_countryspecificlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryspecificdocument',
            old_name='document_name',
            new_name='document_types',
        ),
    ]
