# Generated by Django 4.2.11 on 2024-08-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_document_name_countryspecificdocument_document_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericremark',
            options={'ordering': ['-created'], 'verbose_name': 'Remark', 'verbose_name_plural': 'Remarks'},
        ),
    ]
