# Generated by Django 4.2.11 on 2024-08-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_genericremark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationremark',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
