# Generated by Django 5.0.7 on 2024-09-04 12:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_organization'),
        ('users', '0033_alter_student_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('company_location', models.CharField(max_length=255, verbose_name='Company Location')),
                ('joined_date', models.DateField(verbose_name='Joined Date')),
                ('reliving_date', models.DateField(verbose_name='Reliving Date')),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
