# Generated by Django 5.0.7 on 2024-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='funds_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('received', 'Received'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='medical_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('received', 'Received'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30, null=True),
        ),
    ]
