# Generated by Django 4.2.11 on 2024-09-09 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_partner_on_boarded_by'),
        ('paceapp', '0039_universityagreement'),
        ('core', '0027_applicationattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMUniversityIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('intake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.intake')),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
