# Generated by Django 4.2.11 on 2024-09-11 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0039_universityagreement'),
        ('core', '0030_dynamicfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySpecificField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('fields', models.ManyToManyField(related_name='country_specific_fields', to='core.dynamicfield')),
            ],
            options={
                'verbose_name': 'Country Field Mapping',
                'verbose_name_plural': 'Country Field Mappings',
            },
        ),
    ]
