# Generated by Django 4.2.11 on 2024-09-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_countryspecificfield'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationattribute',
            name='unique_application_key',
        ),
        migrations.RemoveIndex(
            model_name='applicationattribute',
            name='core_applic_applica_d59674_idx',
        ),
        migrations.RemoveField(
            model_name='applicationattribute',
            name='key',
        ),
        migrations.AddField(
            model_name='applicationattribute',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_attributes', to='core.dynamicfield'),
        ),
        migrations.AddIndex(
            model_name='applicationattribute',
            index=models.Index(fields=['application', 'field'], name='core_applic_applica_33001b_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationattribute',
            constraint=models.UniqueConstraint(fields=('application', 'field'), name='unique_application_key'),
        ),
    ]
