# Generated by Django 4.2.11 on 2024-09-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_applicationattribute_unique_application_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryspecificstatus',
            name='achievement_statuses',
            field=models.ManyToManyField(related_name='achievements', to='core.statustype'),
        ),
    ]
