# Generated by Django 4.2.11 on 2024-10-10 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0039_universityagreement'),
        ('core', '0034_application_application_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commission', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(help_text='partner country', on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.university')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
