# Generated by Django 4.2.11 on 2024-10-21 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_student_assessment_requested'),
        ('paceapp', '0039_universityagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_commissionstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.assessmentdiscovery')),
                ('assessment_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
