# Generated by Django 4.2.11 on 2024-10-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0039_universityagreement'),
        ('users', '0044_student_assessment_requested'),
        ('core', '0036_assessmentrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentrequest',
            unique_together={('student', 'university', 'is_active')},
        ),
    ]
