# Generated by Django 4.2.11 on 2024-10-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_interviewstatustype'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_status',
            field=models.ForeignKey(blank=True, help_text='University Interview status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interviewstatustype'),
        ),
    ]
