# Generated by Django 4.2.11 on 2024-10-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0040_country_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_application_interview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOnBoardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(help_text='Company Name', max_length=255, unique=True)),
                ('legal_name', models.CharField(help_text='Registered Company Name', max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, max_length=255, null=True)),
                ('office_type', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_commencement', models.DateField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='partner_onboarding/logo')),
                ('website', models.CharField(blank=True, help_text='Partner website link.', max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('follow-up', 'Follow-up'), ('not-interested', 'Not Interested'), ('interested', 'Interested')], default='new', max_length=30)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('is_agreement_sent', models.BooleanField(default=False)),
                ('blacklisted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('mobile_country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_country_code', to='paceapp.country')),
                ('on_boarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_onboarding', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.state')),
                ('whatsapp_country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_country_code', to='paceapp.country')),
            ],
            options={
                'indexes': [models.Index(fields=['company_name', 'email', 'mobile_number'], name='core_partne_company_a829f1_idx')],
            },
        ),
    ]
