# Generated by Django 4.2.11 on 2024-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_partneronboardingrequest_is_any_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneronboardingrequest',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
