# Generated by Django 4.2.11 on 2024-10-24 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0041_university_alis'),
        ('core', '0042_partneronboardingrequest_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInterviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('status_types', models.ManyToManyField(related_name='university_interview_statuses', to='core.statustype')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_statuses', to='paceapp.university')),
            ],
            options={
                'verbose_name': 'University Interview Status',
                'verbose_name_plural': 'University Interview Statuses',
                'indexes': [models.Index(fields=['university', 'is_active'], name='core_univer_univers_98c5ba_idx')],
            },
        ),
    ]
