# Generated by Django 4.2.11 on 2024-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_universityinterviewstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstatustype',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Mark This Status Type as Mock interview Status Type'),
        ),
    ]
