# Generated by Django 4.2.11 on 2024-10-28 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_interviewstatustype_is_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_activities', to='core.application')),
                ('interview_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interviewstatustype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
