# Generated by Django 4.2.11 on 2024-11-11 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_partner_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_interviewactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='core.application')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned the application', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_application_logs', to='users.employee')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
