# Generated by Django 4.2.11 on 2024-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='core.condition'),
        ),
    ]
