# Generated by Django 4.2.11 on 2024-11-13 07:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paceapp', '0043_course_link_course_scholarship_course_tuition_fees'),
        ('core', '0048_application_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.FileField(blank=True, null=True, upload_to='updates')),
                ('update', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(help_text='update country', on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
