# Generated by Django 4.2.11 on 2024-11-22 06:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_universitycommissiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('from_student', models.IntegerField()),
                ('to_student', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
