# Generated by Django 4.2.11 on 2024-11-22 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paceapp', '0045_university_partially_1_university_partially_2'),
        ('core', '0053_studentslab'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionFromUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commission_in_percent', models.FloatField(blank=True, null=True)),
                ('commission_in_flat', models.FloatField(blank=True, null=True)),
                ('bonus_in_flat', models.FloatField(blank=True, null=True)),
                ('bonus_in_percentage', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.universitycommissiontype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentslab')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
