# Generated by Django 4.2.11 on 2024-11-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0045_university_partially_1_university_partially_2'),
        ('core', '0054_commissionfromuniversity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionfromuniversity',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.intake'),
        ),
        migrations.AddField(
            model_name='commissionfromuniversity',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paceapp.year'),
        ),
    ]
