# Generated by Django 4.2.11 on 2024-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_commissionfromuniversity_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='balance_tuition_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='company_applied_through',
            field=models.CharField(blank=True, choices=[('INFINITE', 'INFINITE'), ('Visa Global', 'Visa Global')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('CO', 'CO'), ('UC', 'UC')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tuition_fee_for_enrollment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tuition_fee_paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
