# Generated by Django 4.2.11 on 2024-04-24 13:37

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('country_currency_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('country_logo', models.FileField(blank=True, null=True, upload_to='country/logo')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
