# Generated by Django 4.2.11 on 2024-04-25 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0005_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('application_accepting_from', models.ManyToManyField(blank=True, related_name='application_accepting_from', to='paceapp.country')),
                ('boards', models.ManyToManyField(blank=True, related_name='boards', to='paceapp.board')),
                ('campus', models.ManyToManyField(to='paceapp.campus')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('states', models.ManyToManyField(blank=True, to='paceapp.state')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
