# Generated by Django 4.2.11 on 2024-04-25 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0006_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150)),
                ('gap_accepted', models.IntegerField(blank=True, null=True)),
                ('entry_criteria', models.FloatField(blank=True, null=True)),
                ('entry_requirement', models.TextField(blank=True, null=True)),
                ('ielts_status', models.BooleanField(default=False)),
                ('pte_status', models.BooleanField(default=False)),
                ('english_marks', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('campus', models.ManyToManyField(to='paceapp.campus')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('intake', models.ManyToManyField(to='paceapp.intake')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.level')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.stream')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
