# Generated by Django 4.2.11 on 2024-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0009_substream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='sub_stream',
            field=models.ManyToManyField(related_name='sub_streams', to='paceapp.substream'),
        ),
    ]
