# Generated by Django 4.2.11 on 2024-04-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0010_stream_is_active_stream_sub_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='streams',
            field=models.ManyToManyField(blank=True, to='paceapp.stream'),
        ),
    ]
