# Generated by Django 4.2.11 on 2024-04-25 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0011_university_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='boards',
            field=models.ManyToManyField(blank=True, to='paceapp.board'),
        ),
        migrations.AddField(
            model_name='level',
            name='streams',
            field=models.ManyToManyField(blank=True, to='paceapp.stream'),
        ),
        migrations.CreateModel(
            name='UniBoardGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gap', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.board')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.state')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
