# Generated by Django 4.2.11 on 2024-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0012_level_boards_level_streams_uniboardgap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='gap_accepted',
        ),
    ]
