# Generated by Django 4.2.11 on 2024-04-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0013_remove_course_gap_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='english_marks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='entry_criteria',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ielts_status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pte_status',
        ),
        migrations.DeleteModel(
            name='IeltsPTE',
        ),
    ]
