# Generated by Django 4.2.11 on 2024-04-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0014_remove_course_english_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='substream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.substream'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.stream'),
        ),
    ]
