# Generated by Django 4.2.11 on 2024-04-26 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0016_englishtesttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tenth_math_marks', models.IntegerField(blank=True, null=True)),
                ('twelfth_math_marks', models.IntegerField(blank=True, null=True)),
                ('twelfth_english_marks', models.IntegerField(blank=True, null=True)),
                ('overall_marks', models.IntegerField(blank=True, null=True)),
                ('best_four_marks', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.board')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
