# Generated by Django 4.2.11 on 2024-04-26 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0017_entrycriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('overall', models.CharField(max_length=150)),
                ('speaking', models.CharField(max_length=150)),
                ('listening', models.CharField(max_length=150)),
                ('writing', models.CharField(max_length=150)),
                ('reading', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.country')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.course')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.englishtesttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
