# Generated by Django 4.2.11 on 2024-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0018_englishtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniboardgap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
