# Generated by Django 4.2.11 on 2024-05-03 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0019_uniboardgap_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityStateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('boards', models.ManyToManyField(to='paceapp.board')),
                ('states', models.ManyToManyField(to='paceapp.state')),
                ('streams', models.ManyToManyField(to='paceapp.stream')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
