# Generated by Django 4.2.11 on 2024-05-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0020_universitystatemapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='university',
            name='states',
        ),
        migrations.RemoveField(
            model_name='university',
            name='streams',
        ),
    ]
