# Generated by Django 4.2.11 on 2024-05-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0021_remove_university_boards_remove_university_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycriteria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
