# Generated by Django 4.2.11 on 2024-06-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0023_pgentrycriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
