# Generated by Django 4.2.11 on 2024-06-24 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_study_level'),
        ('paceapp', '0025_assessmentdiscovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdiscovery',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
