# Generated by Django 4.2.11 on 2024-07-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0027_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'name')},
        ),
    ]
