# Generated by Django 4.2.11 on 2024-07-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0028_alter_region_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.region'),
        ),
    ]
