# Generated by Django 4.2.11 on 2024-07-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0029_state_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
