# Generated by Django 4.2.11 on 2024-07-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_partner_address_alter_partner_company_type_and_more'),
        ('paceapp', '0031_universityintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentdiscovery',
            name='courses',
        ),
        migrations.AddField(
            model_name='assessmentdiscovery',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.course'),
        ),
        migrations.AddField(
            model_name='assessmentdiscovery',
            name='intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.intake'),
        ),
        migrations.AlterField(
            model_name='assessmentdiscovery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
