# Generated by Django 4.2.11 on 2024-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0032_remove_assessmentdiscovery_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityintake',
            options={'ordering': ['university']},
        ),
        migrations.RemoveIndex(
            model_name='universityintake',
            name='paceapp_uni_univers_9388c3_idx',
        ),
        migrations.RemoveField(
            model_name='universityintake',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='universityintake',
            name='year',
        ),
        migrations.AddField(
            model_name='universityintake',
            name='intakes',
            field=models.ManyToManyField(to='paceapp.intake'),
        ),
        migrations.AddIndex(
            model_name='universityintake',
            index=models.Index(fields=['university'], name='paceapp_uni_univers_d19da7_idx'),
        ),
    ]
