# Generated by Django 4.2.11 on 2024-07-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0033_alter_universityintake_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentdiscovery',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paceapp.year'),
        ),
    ]
