# Generated by Django 4.2.11 on 2024-08-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0034_assessmentdiscovery_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['intake_year']},
        ),
    ]
