# Generated by Django 4.2.11 on 2024-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0035_alter_year_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='university/logo'),
        ),
    ]
