# Generated by Django 4.2.11 on 2024-08-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paceapp', '0036_university_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentdiscovery',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
