# Generated by Django 5.0.7 on 2024-08-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0037_assessmentdiscovery_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_active_for_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active_for_university',
            field=models.BooleanField(default=False),
        ),
    ]
