# Generated by Django 4.2.11 on 2024-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0039_universityagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
