# Generated by Django 4.2.11 on 2024-10-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0040_country_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='alis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
