# Generated by Django 4.2.11 on 2024-11-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0041_university_alis'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
