# Generated by Django 4.2.11 on 2024-11-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0042_university_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, help_text='course link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='scholarship',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tuition_fees',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
