# Generated by Django 4.2.11 on 2024-11-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0044_university_commission_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='partially_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='partially_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
