# Generated by Django 4.2.11 on 2024-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0045_university_partially_1_university_partially_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='mini_logo',
            field=models.FileField(blank=True, null=True, upload_to='university/mini_logo'),
        ),
    ]
