# Generated by Django 4.2.11 on 2024-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetcom', '0004_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
