# Generated by Django 4.2.11 on 2024-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetcom', '0005_communication_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
