# Generated by Django 4.2.11 on 2024-07-26 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetcom', '0006_calendarevent_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='meeting',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
