# Generated by Django 4.2.11 on 2024-11-06 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0045_employee_is_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paceapp', '0041_university_alis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('commission_type', models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], default='Percentage', max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commissions', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='users.partner')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='paceapp.university')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
