# Generated by Django 4.2.11 on 2024-11-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paceapp', '0045_university_partially_1_university_partially_2'),
        ('core', '0055_commissionfromuniversity_intake_and_more'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCommissionSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commission', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_on', models.CharField(choices=[('net fee', 'Net Fee'), ('grass fee', 'Grass Fee')], max_length=100)),
                ('bonus', models.CharField(blank=True, max_length=100, null=True)),
                ('tution_fee_for_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('bonus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions_bonus_type', to='core.universitycommissiontype')),
                ('commission_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions_frequency', to='paceapp.university')),
                ('commission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commission_type', to='core.universitycommissiontype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_commissions', to=settings.AUTH_USER_MODEL)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.intake')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.region')),
                ('slabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentslab')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions_university', to='paceapp.university')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paceapp.year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
