# Generated by Django 4.2.11 on 2024-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paceapp', '0045_university_partially_1_university_partially_2'),
        ('partner', '0002_partnercommissionsetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercommissionsetup',
            name='region',
        ),
        migrations.AddField(
            model_name='partnercommissionsetup',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, related_name='partner_commissions_region', to='paceapp.region'),
        ),
    ]
