# Generated by Django 4.2.11 on 2024-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_remove_partnercommissionsetup_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercommissionsetup',
            name='commission_frequency',
            field=models.CharField(blank=True, choices=[('intakewise', 'Intakewise'), ('annually', 'Annually'), ('partially', 'Partially')], max_length=100, null=True),
        ),
    ]
